### ISSUE TITLE
How to fix this？

### ISSUE THREAD

**Issue by KaiJia2017** [actiongpt/actiongpt#4]
![image](https://github.com/actiongpt/actiongpt/assets/32702706/29e7aa2a-08c3-4617-88a7-b91e38b6364f)

**Comment by KaiJia2017** [comment]
G:\Miniconda3\lib\site-packages\hydra\_internal\hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(

Error executing job with overrides: ['folder=/path/to/experiment', 'output=/path/to/yourfname', "texts='[run]'", "durs='[1]'"]
Traceback (most recent call last):
  File "G:\GitFork\actiongpt\Action-GPT_TEACH_k-4\interact_teach.py", line 35, in _interact
    return interact(cfg)
  File "G:\GitFork\actiongpt\Action-GPT_TEACH_k-4\interact_teach.py", line 45, in interact
    prevcfg = OmegaConf.load(output_dir / ".hydra/config.yaml")
FileNotFoundError: [Errno 2] No such file or directory: 'G:\\path\\to\\experiment\\.hydra\\config.yaml'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
